config/routes.rb
Rails.application.routes.draw do

  get "carts/cart_ccc" => "carts#cart_ccc", as: "ccc"
  post "carts/:user_id/:total_price" => "carts#cart_last", as: "last"
  post "carts/purchase_singles" => "carts#cart_single", as:"single"

  namespace :admins do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :products do
      resources :discs do
        resources :tunes
      end
    end

    resources :discs
    resources :artists
    resources :purchases
    resources :admins
    resources :genres
    resources :labels
  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
    }

  post "products/:product_id/carts/" => "carts#add_carts", as: "sss"
  root to: 'products#index'

  get 'admins/' => 'admins#index', as: :admins

  resources :users, only: [:show, :edit, :destroy, :update]
  resources :carts, only: [:index, :destroy, :update]
  resources :purchases
  resources :destinations
  resources :products do
    collection do
      get :search
    end
  end
  resources :purchase_singles
  resources :unsubscribes
  resources :tunes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Artist.where(['name LIKE ?', "%#{search}%"])
		else
			Artist.all
		end
	end

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :product
	belongs_to :user

	validates :sheet_number, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :sheet_number, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
	belongs_to :user

	validates :postal_code, presence: true
  validates :destination, presence: true

end

app/models/disc.rb
class Disc < ApplicationRecord

	has_many :tunes
	belongs_to :product

  accepts_nested_attributes_for :tunes, allow_destroy: true, reject_if: :all_blank


end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Genre.where(['name LIKE ?', "%#{search}%"])
		else
			Genre.all
		end
	end

end

app/models/label.rb
class Label < ApplicationRecord

	has_many :products

	validates :name, presence: true

	def self.search(search)
		if search
			Label.where(['name LIKE ?', "%#{search}%"])
		else
			Label.all
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord

	has_many :carts
  has_many :users, through: :carts
	has_many :discs
	has_many :purchase_singles
  belongs_to :label

	validates :title, presence: true
	validates :label_id, presence: true
	validates :price, presence: true
	validates :image, presence: true
	validates :release_date, presence: true
	validates :stock_count, presence: true
	validates :disc_count, presence: true

	attachment :image

  accepts_nested_attributes_for :discs

	def self.search(search)
    if search
    Product.where(['title LIKE ?', "%#{search}%"])
    else
    Product.all
    end

  end

end

app/models/purchase.rb
class Purchase < ApplicationRecord

	has_many :purchase_singles
	belongs_to :user


	enum status: { 商品準備中: 0, 出荷済: 1 }

	def self.search(search)
		if search
			Purchase.where(['created_at LIKE ?', "%#{search}%"])
		else
			Purchase.all
		end
	end

end

app/models/purchase_single.rb
class PurchaseSingle < ApplicationRecord

	belongs_to :purchase
	belongs_to :product

end

app/models/tune.rb
class Tune < ApplicationRecord

	belongs_to :disc
	belongs_to :artist
	belongs_to :genre

	validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :destinations
  accepts_nested_attributes_for :destinations, allow_destroy: true, reject_if: :all_blank

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  has_many :carts
  has_many :products, through: :carts
  has_many :destinations
  has_many :purchases

  validates :name_family_name, presence: true

  validates :name_name, presence: true

  validates :furigana_family_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :furigana_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :postal_code, presence: true, format: {
                    with: /\A\d{3}\-?\d{4}\z/
                 }

  validates :address, presence: true

  validates :phone_number, presence: true, format: {
                    with: /\A\d{10}$|^\d{11}\z/
                  }

  def self.search(search)
    if search
      User.where(['email LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admins/_list.html.erb
<h1>リストだよ</h1>
<nav>
  <ul>
    <li><%= link_to "会員の一覧", admins_users_path, class: "aaa" %></li>
    <li><%= link_to "アーティストの登録", new_admins_artist_path, class: "aaa" %></li>
    <li><%= link_to "レーベルの登録", new_admins_label_path, class: "aaa" %></li>
    <li><%= link_to "ジャンルの登録", new_admins_genre_path, class: "aaa" %></li>
    <li><%= link_to "商品の登録", new_admins_product_path, class: "aaa" %></li>
    <li><%= link_to "商品の一覧", admins_products_path, class: "aaa" %></li>
    <li><%= link_to "購入履歴", admins_purchases_path, class: "aaa" %></li>
  </ul>
</nav>

app/views/admins/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-7 col-xs-offset-2">
			<h1 class="h1">管理者TOP</h1>
        </div>
    </div>

    <div class="row">
    	<div class="col-xs-3 col-xs-offset-2">
    		<h2>登録</h2>
    		<div><%= link_to "アーティスト", new_admins_artist_path, class: "aaa" %></div>
    		<div><%= link_to "ジャンル", new_admins_genre_path, class: "aaa" %></div>
    		<div><%= link_to "レーベル", new_admins_label_path, class: "aaa" %></div>
    		<div><%= link_to "商品", new_admins_product_path, class: "aaa" %></div>
    	</div>
    	<div class="col-xs-3">
    		<h2>一覧</h2>
    		<div><%= link_to "アーティスト", admins_artists_path, class: "aaa" %></div>
    		<div><%= link_to "ジャンル", admins_genres_path, class: "aaa" %></div>
    		<div><%= link_to "レーベル", admins_labels_path, class: "aaa" %></div>
    		<div><%= link_to "商品", admins_products_path, class: "aaa" %></div>
            <div><%= link_to "会員", admins_users_path, class: "aaa" %></div>
    	</div>
    	<div class="col-xs-3">
    		<h2>その他</h2>
    		<%= link_to "購入履歴", admins_purchases_path, class: "aaa" %>
    	</div>
    </div>
</div>