config/routes.rb
Rails.application.routes.draw do

  get "carts/cart_ccc" => "carts#cart_ccc", as: "ccc"
  post "carts/:user_id/:total_price" => "carts#cart_last", as: "last"
  post "carts/purchase_singles" => "carts#cart_single", as:"single"

  namespace :admins do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :products do
      resources :discs do
        resources :tunes
      end
    end

    resources :discs
    resources :artists
    resources :purchases
    resources :admins
    resources :genres
    resources :labels
  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
    }

  post "products/:product_id/carts/" => "carts#add_carts", as: "sss"
  root to: 'products#index'

  get 'admins/' => 'admins#index', as: :admins

  resources :users, only: [:show, :edit, :destroy, :update]
  resources :carts, only: [:index, :destroy, :update]
  resources :purchases
  resources :destinations
  resources :products do
    collection do
      get :search
    end
  end
  resources :purchase_singles
  resources :unsubscribes
  resources :tunes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :product
	belongs_to :user

	validates :sheet_number, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :sheet_number, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!


	def index
		@carts = Cart.where(user_id: current_user.id).page(params[:page]).reverse_order
	 	 #@carts = Cart.where(user_id: current_user.id)

	end

	def update
		carts = Cart.find(params[:id])
		carts.update(cart_params)
		redirect_to carts_path
	end

	# def cart_ccc
	# 	@user = User.find(current_user.id)
	# 	# @cart = Cart.all
	# 	binding.pry
	# 	@carts = Cart.where(user_id: 2)
	# 	@purchase = @user.purchases.new
	# 	@destinations = @user.destinations

	# 	@destinations_array = []
	# 	@destinations.each do |destination|
	# 		@destinations_array << [destination.destination, destination.id]
	# 	end
	# end

	def cart_ccc
		if current_user.carts.present?
		@purchase = current_user.purchases.new
		@destinations = current_user.destinations
			# if @destinations.present?
				@destinations_array = []
				@destinations_array << [current_user.address,current_user.address]
				@destinations.each do |destination|
	 			@destinations_array << [destination.destination,destination.destination]
	 				end
			# else
			# 	@destinations_array = []

			# 	@destinations_array << [current_user.address,current_user.address]
			# end
		else
			redirect_to root_path
	 	end

	end

	def cart_last

		carts = Cart.where(params[:id])


		purchase = Purchase.new(user_id: current_user.id, total_price: params[:total_price], destination: purchase_params[:destination], status: 0)

        purchase.save
        carts.each do |cart|
        purchase_single = PurchaseSingle.new(purchase_id: purchase.id, product_id: cart.product_id, sheet_number: cart.sheet_number)
        purchase_single.save
        cart.product.stock_count -= cart.sheet_number
        cart.product.save
		cart.destroy

		end
		redirect_to root_path, notice: "まいど！！"
	end

	def destroy
		cart = Cart.find(params[:id])
		cart.destroy
		redirect_to carts_path
	end

	def add_carts
		if params["cart"]["sheet_number"] == ""
			# flash[:notice] = "カートに商品入れてください"
			redirect_to root_path, notice: "何か入れて！！！"
		else
			add_cart = Cart.new(cart_params)
				product = Product.find(params[:product_id])
				 if Cart.exists?(user_id: current_user.id ,product_id: params[:product_id])
				 	cart = Cart.find_by(user_id: current_user.id ,product_id: params[:product_id])
				 	cart.sheet_number = cart.sheet_number + add_cart.sheet_number
				 	if cart.sheet_number <= product.stock_count
				 		cart.save
				 		redirect_to carts_path
				 	else
				 		redirect_to product_path(product), notice: "在庫は#{product.stock_count}枚だよ！"
				 	end

				else
				 	# cart = Cart.new(cart_params)
					add_cart.product_id = params[:product_id]
					add_cart.user_id = current_user.id
					# 枚数はパラメーター(ストロングパラメーター)
					if add_cart.sheet_number < product.stock_count
				 		add_cart.save
						redirect_to carts_path
				 	else
				 		redirect_to product_path(product), notice: "在庫は#{product.stock_count}枚だよ！"
				 	end
				end
		end
	end



	private
	    # cart_params[]

		def cart_params
        	params.require(:cart).permit(:product_id, :sheet_number, :user_id)
    	end

    	def purchase_params
        	params.require(:purchase).permit(:destination, :status, :user_id, :total_price)
    	end

    	def purchase_single_params
            params.require(:purchase_single).permit(:purchase_id, :product_id, :sheet_numer)
    	end
    	# def cart_ccc
    	# 	params.require(:user).permit(:user_id)
    	# end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/cart_ccc.html.erb
<div class="row text-center" style="padding: 200px 0 300px 0;">
<div class="col-lg-3"></div>
<div class="col-lg-6">
	<div class="row" style="background-color: #ffffff; border: double;">
    <table style="border-collapse: separate; border-spacing: 10px;">
	<% @price = 0 %>
	<% current_user.carts.each do |cart| %>
	<tr>
	  <td>Title：<%= cart.product.title %></td>
	  <td>購入枚数：<%= cart.sheet_number %>枚</td>
	  <td>値段：<%= cart.product.price %> 円</td>
      <td>小計：<%= cart.product.price * cart.sheet_number %>円</td>
    </tr>
	<% total_price = cart.product.price * cart.sheet_number %>
	<% @price += total_price %>
	<% end %>
  </table>
</div>
<div class="row" style="background-color: #ffffff; border: double; margin-top: 30px;" >
	合計<%= @price %>円
    <%= form_for (@purchase), url:last_path(user_id: current_user.id,total_price: @price) do |f| %>

    送付先選択<%= f.select :destination, @destinations_array %>

	<%= f.submit "購入する"%>
<% end %>
</div>
</div>
<div class="col-lg-3"></div>
</div>

app/views/carts/index.html.erb
<div class="row text-center" style="padding-top: 150px;padding-bottom: 150px;">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
  	<h2 style="color: white;">カート</h2>
    <% if @carts.present? %>
  	<%@carts.each do |cart| %>
      <div class="row" style="background-color: #ffffff; height: 200px; border: double; margin-top: 60px;">
        <div class="col-lg-4" style="height: 100%;">
          <%= attachment_image_tag cart.product, :image, format: 'jpeg', fallback: "no_image.jpg", style: "height: 100%; width: 194px;" %>
        </div>
        <div class="col-lg-8" style="height: 100%;">
          <table class="table text-left" style="margin-top: 40px;">
            <tbody>
              <tr>
                <td><%= cart.product.title %></td>
                    <% a = [] %>
                    <% cart.product.discs.each do |disc| %>
                      <% disc.tunes.each do |tune| %>
                        <% a.push(tune.artist.name) %>
                      <% end %>
                    <% end %>
                <td><%= a.max_by { |v| a.count(v)} %></td>
              </tr>
              <tr>
                <td><%= cart.product.price %>円</td>
                <td><% s = cart.product.stock_count %>
                    <% if s == 0 %>
                      売り切れ
                    <% elsif s >= 1 && s <= 10 %>
                      在庫残りわずか
                    <% else s >= 11 %>
                      在庫有り
                    <% end %>
                    <%= s %></td>
              </tr>
            </tbody>
          </table>
          <div class="text-left">
            <%= form_for(cart) do |f| %>
              <%= f.label :枚数 %>
              <%= f.number_field :sheet_number, class:"number-field", :min => "1", :max => "99" %>
              <%= f.submit "更新する" %>
              <%= link_to'カートから出す',cart_path(cart.id), method: :delete, "data-confirm" => "本当にカートから出しますか？" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row" style="background-color: #ffffff; height: 100px; border: double; margin-top: 60px;">
      <div class="col-lg-3"></div>
      <div class="col-lg-3" style="padding-top: 35px;">
        <%= link_to '購入ページへ', ccc_path %>
      </div>
      <div class="col-lg-3" style="padding-top: 35px;">
        <%= link_to "お買い物を続ける", products_path %>
      </div>
    <div class="col-lg-3"></div>
    </div>
    <% else %>
    <p style="color: white;">カートは空です。</p>
    <h1 style="color: white;">なんか買ってね！！！</h1>
    <% end %>
    <%= paginate @carts, class: "pagenate" %>
  </div>
  <div class="col-lg-3"></div>
</div>