config/routes.rb
Rails.application.routes.draw do

  get "carts/cart_ccc" => "carts#cart_ccc", as: "ccc"
  post "carts/:user_id/:total_price" => "carts#cart_last", as: "last"
  post "carts/purchase_singles" => "carts#cart_single", as:"single"

  namespace :admins do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :products do
      resources :discs do
        resources :tunes
      end
    end

    resources :discs
    resources :artists
    resources :purchases
    resources :admins
    resources :genres
    resources :labels
  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
    }

  post "products/:product_id/carts/" => "carts#add_carts", as: "sss"
  root to: 'products#index'

  get 'admins/' => 'admins#index', as: :admins

  resources :users, only: [:show, :edit, :destroy, :update]
  resources :carts, only: [:index, :destroy, :update]
  resources :purchases
  resources :destinations
  resources :products do
    collection do
      get :search
    end
  end
  resources :purchase_singles
  resources :unsubscribes
  resources :tunes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Artist.where(['name LIKE ?', "%#{search}%"])
		else
			Artist.all
		end
	end

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :product
	belongs_to :user

	validates :sheet_number, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :sheet_number, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
	belongs_to :user

	validates :postal_code, presence: true
  validates :destination, presence: true

end

app/models/disc.rb
class Disc < ApplicationRecord

	has_many :tunes
	belongs_to :product

  accepts_nested_attributes_for :tunes, allow_destroy: true, reject_if: :all_blank


end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Genre.where(['name LIKE ?', "%#{search}%"])
		else
			Genre.all
		end
	end

end

app/models/label.rb
class Label < ApplicationRecord

	has_many :products

	validates :name, presence: true

	def self.search(search)
		if search
			Label.where(['name LIKE ?', "%#{search}%"])
		else
			Label.all
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord

	has_many :carts
  has_many :users, through: :carts
	has_many :discs
	has_many :purchase_singles
  belongs_to :label

	validates :title, presence: true
	validates :label_id, presence: true
	validates :price, presence: true
	validates :image, presence: true
	validates :release_date, presence: true
	validates :stock_count, presence: true
	validates :disc_count, presence: true

	attachment :image

  accepts_nested_attributes_for :discs

	def self.search(search)
    if search
    Product.where(['title LIKE ?', "%#{search}%"])
    else
    Product.all
    end

  end

end

app/models/purchase.rb
class Purchase < ApplicationRecord

	has_many :purchase_singles
	belongs_to :user


	enum status: { 商品準備中: 0, 出荷済: 1 }

	def self.search(search)
		if search
			Purchase.where(['created_at LIKE ?', "%#{search}%"])
		else
			Purchase.all
		end
	end

end

app/models/purchase_single.rb
class PurchaseSingle < ApplicationRecord

	belongs_to :purchase
	belongs_to :product

end

app/models/tune.rb
class Tune < ApplicationRecord

	belongs_to :disc
	belongs_to :artist
	belongs_to :genre

	validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :destinations
  accepts_nested_attributes_for :destinations, allow_destroy: true, reject_if: :all_blank

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  has_many :carts
  has_many :products, through: :carts
  has_many :destinations
  has_many :purchases

  validates :name_family_name, presence: true

  validates :name_name, presence: true

  validates :furigana_family_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :furigana_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :postal_code, presence: true, format: {
                    with: /\A\d{3}\-?\d{4}\z/
                 }

  validates :address, presence: true

  validates :phone_number, presence: true, format: {
                    with: /\A\d{10}$|^\d{11}\z/
                  }

  def self.search(search)
    if search
      User.where(['email LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/admins/artists_controller.rb
class Admins::ArtistsController < ApplicationController
  before_action :authenticate_admin!
	layout "admins"

	def index
		@artists = Artist.page(params[:page]).reverse_order
		artistsx = Artist.search(params[:search])
		@artists_search = artistsx.page(params[:page]).reverse_order
	end

	def show
	  @artist = Artist.find(params[:id])
    @tune = Tune.all
	end

	def new
	  @artist = Artist.new
	end

	def create
	  @artist = Artist.new(artist_params)
	  if @artist.save
			flash[:notice] = "アーティスト名登録完了"
	  	redirect_to admins_artists_path
		else
			render :new
		end
	end

	def edit
	  @artist = Artist.find(params[:id])
	end

	def update
	  @artist = Artist.find(params[:id])
	  if @artist.update(artist_params)
			flash[:notice] = "アーティスト名編集完了"
	  	redirect_to admins_artist_path(@artist.id)
		else
			render :edit
		end
	end

	def destroy
	  @artist = Artist.find(params[:id])
	  @artist.destroy
	  redirect_to admins_artists_path
	end

	private
	def artist_params
	  params.require(:artist).permit(:name)
	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/helpers/admins/artists_helper.rb
module Admins::ArtistsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admins/artists/edit.html.erb
<h1>アーティストの編集</h1>

<% if flash[:notice] %>
  <div class="flash" style="color: green;">
    <%= flash[:notice] %>
  </div>
<% end %>

<h3><%= form_for [:admins, @artist] do |f| %></h3>

<% if @artist.errors.any? %>
  <h2><%= @artist.errors.count %>件のエラーが発生しました</h2>
  <ul>
    <% @artist.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= f.text_field :name %>
<%= f.submit '保存' %>
<%end%>

<h3><%= link_to '戻る', admins_artist_path(@artist.id) %></h3>

app/views/admins/artists/index.html.erb
<h1>アーティスト一覧</h1>

<% if flash[:notice] %>
  <div class="flash" style="color: green;">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= form_tag admins_artists_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "検索", :name => nil %>
    </p>
<% end %>

<% @artists_search.each do |f| %>
  <p><%= link_to f.name, edit_admins_artist_path(f.id) %></p>
<%end%>

<%= paginate @artists_search %>

<h3><%= link_to "登録ページ", new_admins_artist_path %></h3>

app/views/admins/artists/new.html.erb
<h1>アーティストの登録</h1>

<%= form_for [:admins, (@artist)] do |f| %>

				<% if @artist.errors.any? %>
				<h2><%= @artist.errors.count %>件のエラーが発生しました</h2>
				<ul>
					<% @artist.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
				<% end %>

				<%= f.text_field :name %>
				<%= f.submit "登録" %>
				<% end %>

				<h3><%= link_to "一覧", admins_artists_path %></h3>

			</div>
		</div>
	</div>
</body>

app/views/admins/artists/show.html.erb
<h1>Admins::Artists#show</h1>

<% if flash[:notice] %>
  <div class="flash" style="color: green;">
    <%= flash[:notice] %>
  </div>
<% end %>

<h3><%= @artist.name %></h3>

<% @artist.tunes.each do |t|%>
<p><%= t.title %></p>
<% end %>

<h3><%= link_to "一覧", admins_artists_path %></h3>

<h3><%= link_to "編集", edit_admins_artist_path(@artist.id) %></h3>

<h3><%= link_to "削除", admins_artist_path(@artist.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></h3>