config/routes.rb
Rails.application.routes.draw do

  get "carts/cart_ccc" => "carts#cart_ccc", as: "ccc"
  post "carts/:user_id/:total_price" => "carts#cart_last", as: "last"
  post "carts/purchase_singles" => "carts#cart_single", as:"single"

  namespace :admins do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :products do
      resources :discs do
        resources :tunes
      end
    end

    resources :discs
    resources :artists
    resources :purchases
    resources :admins
    resources :genres
    resources :labels
  end

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
    }

  post "products/:product_id/carts/" => "carts#add_carts", as: "sss"
  root to: 'products#index'

  get 'admins/' => 'admins#index', as: :admins

  resources :users, only: [:show, :edit, :destroy, :update]
  resources :carts, only: [:index, :destroy, :update]
  resources :purchases
  resources :destinations
  resources :products do
    collection do
      get :search
    end
  end
  resources :purchase_singles
  resources :unsubscribes
  resources :tunes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Artist.where(['name LIKE ?', "%#{search}%"])
		else
			Artist.all
		end
	end

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :product
	belongs_to :user

	validates :sheet_number, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :sheet_number, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
	belongs_to :user

	validates :postal_code, presence: true
  validates :destination, presence: true

end

app/models/disc.rb
class Disc < ApplicationRecord

	has_many :tunes
	belongs_to :product

  accepts_nested_attributes_for :tunes, allow_destroy: true, reject_if: :all_blank


end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :tunes

	validates :name, presence: true

	def self.search(search)
		if search
			Genre.where(['name LIKE ?', "%#{search}%"])
		else
			Genre.all
		end
	end

end

app/models/label.rb
class Label < ApplicationRecord

	has_many :products

	validates :name, presence: true

	def self.search(search)
		if search
			Label.where(['name LIKE ?', "%#{search}%"])
		else
			Label.all
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord

	has_many :carts
  has_many :users, through: :carts
	has_many :discs
	has_many :purchase_singles
  belongs_to :label

	validates :title, presence: true
	validates :label_id, presence: true
	validates :price, presence: true
	validates :image, presence: true
	validates :release_date, presence: true
	validates :stock_count, presence: true
	validates :disc_count, presence: true

	attachment :image

  accepts_nested_attributes_for :discs

	def self.search(search)
    if search
    Product.where(['title LIKE ?', "%#{search}%"])
    else
    Product.all
    end

  end

end

app/models/purchase.rb
class Purchase < ApplicationRecord

	has_many :purchase_singles
	belongs_to :user


	enum status: { 商品準備中: 0, 出荷済: 1 }

	def self.search(search)
		if search
			Purchase.where(['created_at LIKE ?', "%#{search}%"])
		else
			Purchase.all
		end
	end

end

app/models/purchase_single.rb
class PurchaseSingle < ApplicationRecord

	belongs_to :purchase
	belongs_to :product

end

app/models/tune.rb
class Tune < ApplicationRecord

	belongs_to :disc
	belongs_to :artist
	belongs_to :genre

	validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :destinations
  accepts_nested_attributes_for :destinations, allow_destroy: true, reject_if: :all_blank

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  has_many :carts
  has_many :products, through: :carts
  has_many :destinations
  has_many :purchases

  validates :name_family_name, presence: true

  validates :name_name, presence: true

  validates :furigana_family_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :furigana_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  validates :postal_code, presence: true, format: {
                    with: /\A\d{3}\-?\d{4}\z/
                 }

  validates :address, presence: true

  validates :phone_number, presence: true, format: {
                    with: /\A\d{10}$|^\d{11}\z/
                  }

  def self.search(search)
    if search
      User.where(['email LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!

  layout "admins"

  def index
    @products = Product.page(params[:page]).reverse_order
    productx = Product.search(params[:search])
    @products_search = productx.page(params[:page]).reverse_order
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @product.disc_count.times do |num|
        disc = Disc.new
        disc.product_id = @product.id
        disc.save
      end
        redirect_to edit_admins_product_path(@product.id)
        flash[:notice] = "disc情報を登録して下さい"
    else
      render :new
    end
  end



  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admins_product_path
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admins_products_path
  end

  private
  def product_params
    params.require(:product).permit(:image, :title, :label_id, :price, :release_date, :stock_count, :disc_count, :disc,
    discs_attributes: [:id, :disc_id, :_destroy] )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def show
        @product = Product.find(params[:id])
        @cart = Cart.new
    end


    def index
  	  productx = Product.search(params[:search])
      @products = productx.page(params[:page]).reverse_order
      @product = Product.all
      @cart = Cart.new
    end

	  def new
		  @product = Product.new
      render :layout => 'admins'
	  end

    def create
      @product = Product.new(product_params)
      @product.save
      redirect_to new_product_path
    end

	private
    def product_params
      params.require(:product).permit(:title, :label, :price, :image, :release_date, :stock_count, :disc_count)
    end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/products/_top.html.erb
<div class="top-image-box">
<% r = 0 %>
<% a = (1..10).to_a.sample(10) %>

<% @product.last(10).each do |product| %>
<div class="image-box<%= a[r] %>" style="display: none;">
  <%= link_to product_path(product.id) do %>
    <%= attachment_image_tag product, :image, format:'jpeg', style:"height: 100%; width: 100%;" %>
  <% end %>
  </div>
  <script>
  	$(function(){
  		$('.image-box<%= a[r] %>').fadeIn(<%= a[r] %> * 1500);
  	});
  </script>
<% r += 1 %>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>プロダクトの編集ページだよ</h1>

app/views/products/index.html.erb
<% url = request.url %>
<% if !url.include?("search") %>
<%= render 'products/top' %>
<% end %>
<div class="row" style="padding-top: 150px">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% if @products.empty? %>
<h2 class="text-center" style="color: white;">一致する商品がありません！</h2>
<% else %>
<% @products.each do |product| %>
<div class="row" style="background-color: #ffffff; height: 200px; border: double; margin-top: 60px;">
  <div class="col-lg-4" style="height: 100%;">
<%= link_to product_path(product.id) do %>

	  <%= attachment_image_tag product, :image, format:'jpeg', fallback: "no_image.jpg", style: "height: 100%; width: 194px;", class:"product-image" %>
  <% end %>
</div>
    <div class="col-lg-8">
      <table class="table" style="margin-top: 40px;">
        <tbody>
          <tr>
            <td><%= link_to product.title, product_path(product.id) %></td>
                <% a = [] %>
                <% product.discs.each do |disc| %>
                  <% disc.tunes.each do |tune| %>
                    <% a.push(tune.artist.name) %>
                  <% end %>
                <% end %>
            <td><%= a.max_by { |v| a.count(v)} %></td>
          </tr>
          <tr>
            <td><%= product.price %>円</td>
            <td><% s = product.stock_count %>
                  <% if s == 0 %>
                    売り切れ
                  <% elsif s >= 1 && s <= 10 %>
                    在庫残りわずか
                  <% else s >= 11 %>
                    在庫有り
                  <% end %>
                  <%= s %></td>
          </tr>
        </tbody>
      </table>
        <% if user_signed_in? %>
          <%= form_for (@cart),url: sss_path(product_id: product) do |f| %>
          <%= f.label :枚数 %>
          <%= f.number_field :sheet_number, class:"number-field", :min => "1", :max => "99" %>
          <%= f.submit("カート追加") %>
          <% end %>
        <% end %>
    </div>
  </div>
  <% end %>
 <% end %>
 <div class="text-center"><%= paginate @products, class: "pagenate" %></div>
  <div class="col-lg-3"></div>
  </div>

app/views/products/new.html.erb
<h1>商品の登録ページだよ</h1>

<%= form_for(@product) do |f| %>

  <div class="field">
    <label for="title">title</label>
    <br>
    <%= f.text_field :title, class: "title" %>
  </div>

  <div class="field">
    <label for="label">label</label>
    <br>
    <%= f.text_field :label, class: "label" %>
  </div>

  <div class="field">
    <label for="price">price</label>
    <br>
    <%= f.text_field :price, class: "price" %>
  </div>

  <div class="field">
    <label for="image_id">image</label>
    <br>
    <%= f.attachment_field :image, placeholder:"ジャケット画像", class:"image_id" %>
  </div>

  <div class="field">
    <label for="release_date">release_date</label>
    <br>
    <%= f.text_field :release_date, class: "release_date" %>
  </div>

  <div class="field">
    <label for="stock_count">stock_count</label>
    <br>
    <%= f.text_field :stock_count, class: "stock_count" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/show.html.erb
<div class="row" style="padding-top: 150px;padding-bottom: 150px;">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
        <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
        <% end %>
    <div class="row" style="background-color: #ffffff; height:200px; border: double;">
      <div class="col-lg-4" style="height: 100%;">
        <%= attachment_image_tag @product, :image, format: 'jpeg', style: "height: 100%; width: 194px;"%>
      </div>

      <div class="col-lg-8">
        <table class="table" style="margin-top: 40px;">
        <tbody>
          <tr>
          <td><%= @product.title %></td>
              <% a = [] %>
              <% @product.discs.each do |disc| %>
                <% disc.tunes.each do |tune| %>
                  <% a.push(tune.artist.name) %>
                <% end %>
              <% end %>
              <td><%= a.max_by { |v| a.count(v)} %></td>
          </tr>
          <tr>
          <td><%= @product.price %>円</td>
          <td><% s = @product.stock_count %>
              <% if s == 0 %>
                在庫無し
              <% elsif s >= 1 && s <= 10 %>
                在庫わずか
              <% else s >= 11 %>
                在庫有り
              <% end %>
              <%= s %></td>
          </tr>
          </tbody>
          </table>
          <% if user_signed_in? %>
            <%= form_for (@cart),url: sss_path(product_id: @product) do |f| %>
            <%= f.label :枚数 %>
            <%= f.number_field :sheet_number, class:"number-field", :min => "1", :max => "99" %>
            <%= f.submit("カート追加") %>
            <% end %>
          <% end %>
  </div>
</div>

    <% b = 1 %>
    <% @product.discs.each do |disc| %>
    <div class="show-tune-box">
    disc<%= b %>
    <table>
      <tr>
      	<th style="padding-left: 10px">曲順</th>
	    <th style="padding-left: 20px">曲名</th>
	    <th style="padding-left: 30px">アーティスト名</th>
      </tr>
      <% c = 1 %>
      <% disc.tunes.each do |tune| %>
      <tr>
      	<td style="padding-left: 10px"><%= c %></td>
	    <td style="padding-left: 20px"><%= tune.title %></td>
        <td style="padding-left: 30px"><%= tune.artist.name %></td>
      </tr>
      <% c += 1 %>
      <% end %>
    </table>
    <% b += 1 %>
    </div>
    <% end %>
  </div>
  <div class="col-lg-3"></div>
</div>